# Generated by Django 5.0.6 on 2024-10-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_deposit_balance_rename_enrollment_enroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
